#include <compression/Crc32.hpp>
#include <compression/codec/CodecRegistry.hpp>
#include <compression/codec/ParallelCodecDecorator.hpp>
#include <compression/core/Errors.hpp>
#include <compression/core/Executor.hpp>
#include <compression/format/FrameRegistry.hpp>

#include <gtest/gtest.h>

#include <cstdint>
#include <memory>
#include <string>
#include <vector>

using namespace compression;
using namespace compression::codec;
using namespace compression::core;

namespace {

// Golden fixtures frozen from the 2.0.0 build. Regenerating them after a
// format change is a deliberate, reviewed act; a drift here means the byte
// layout changed and 1.x/2.x files would no longer interoperate.
//
// The fixtures themselves live in GoldenFixtures.inc (hex string literals)
// and are generated by the golden-fixture generator from this build.
//
// Input for all fixtures: the 19-byte ASCII text "the quick brown fox".
//
// PLIN pipeline frame layout (PipelineCodec):
//   [4] "PLIN" magic
//   [1] version (1)
//   [1] stage count
//   [N] transform ids (BWT=1, RLE=2)
//   [1] coder id (Arithmetic=1, ANS=2)
//   [M] coder payload
//
// ANS payload layout (AnsCoder):
//   [512] 256 x u16 LE frequencies (sum 2^16, each <= 2^15)
//   [4]   u32 LE symbol count
//   [4]   u32 LE final encoder state
//   [..]  renormalization bytes, in reverse emission order
//
// CPRO container layout (serializeHeader):
//   [4] "CPRO" magic
//   [1] format version (1)
//   [1] algorithm id (ANS=10, OPTIMIZED=7)
//   [8] u64 LE original size
//   [4] u32 LE CRC32 of the original data
//   [4] u32 LE chunk count
//   [4] u32 LE chunk size
//   [4 x chunk count] u32 LE per-chunk compressed sizes
//   [..] concatenated chunk payloads

#include "GoldenFixtures.inc"

std::vector<uint8_t> fromHex(const char *hex) {
  std::vector<uint8_t> bytes;
  bytes.reserve(std::string(hex).size() / 2);
  for (const char *p = hex; p[0] != '\0' && p[1] != '\0'; p += 2) {
    auto nibble = [](char c) -> uint8_t {
      if (c >= '0' && c <= '9') return static_cast<uint8_t>(c - '0');
      return static_cast<uint8_t>(10 + (c - 'A'));
    };
    bytes.push_back(static_cast<uint8_t>((nibble(p[0]) << 4) | nibble(p[1])));
  }
  return bytes;
}

std::vector<uint8_t> sampleInput() {
  return {'t', 'h', 'e', ' ', 'q', 'u', 'i', 'c', 'k', ' ',
          'b', 'r', 'o', 'w', 'n', ' ', 'f', 'o', 'x'};
}

std::unique_ptr<ICompressor> framed(format::AlgorithmID id,
                                    core::IExecutor *executor) {
  return std::make_unique<ParallelCodecDecorator>(
      CodecRegistry::instance().create(id), id, executor, 1);
}

} // namespace

TEST(GoldenTest, AnsPayloadBytesAreStable) {
  const auto codec = CodecRegistry::instance().create("ans");
  ASSERT_NE(codec, nullptr);
  EXPECT_EQ(codec->compress(sampleInput()), fromHex(kAnsPayloadHex));
}

TEST(GoldenTest, Bwt2PayloadBytesAreStable) {
  const auto codec = CodecRegistry::instance().create("bwt2");
  ASSERT_NE(codec, nullptr);
  EXPECT_EQ(codec->compress(sampleInput()), fromHex(kBwt2PayloadHex));
}

TEST(GoldenTest, AnsFixtureDecompressesToInput) {
  const auto codec = CodecRegistry::instance().create("ans");
  ASSERT_NE(codec, nullptr);
  EXPECT_EQ(codec->decompress(fromHex(kAnsPayloadHex)), sampleInput());
}

TEST(GoldenTest, Bwt2FixtureDecompressesToInput) {
  const auto codec = CodecRegistry::instance().create("bwt2");
  ASSERT_NE(codec, nullptr);
  EXPECT_EQ(codec->decompress(fromHex(kBwt2PayloadHex)), sampleInput());
}

TEST(GoldenTest, CproAnsFrameBytesAreStable) {
  core::InlineExecutor executor;
  auto codec = framed(format::AlgorithmID::ANS_COMPRESSOR, &executor);
  EXPECT_EQ(codec->compress(sampleInput()), fromHex(kCproAnsFrameHex));
}

TEST(GoldenTest, CproOptimizedFrameBytesAreStable) {
  core::InlineExecutor executor;
  auto codec = framed(format::AlgorithmID::OPTIMIZED_COMPRESSOR, &executor);
  EXPECT_EQ(codec->compress(sampleInput()), fromHex(kCproOptimizedFrameHex));
}

TEST(GoldenTest, CproAnsFixtureDecompressesToInput) {
  core::InlineExecutor executor;
  auto codec = framed(format::AlgorithmID::ANS_COMPRESSOR, &executor);
  EXPECT_EQ(codec->decompress(fromHex(kCproAnsFrameHex)), sampleInput());
}

TEST(GoldenTest, CproAnsFixtureHeaderFields) {
  const format::FileHeader header =
      format::deserializeHeader(fromHex(kCproAnsFrameHex));
  EXPECT_EQ(header.formatVersion, format::FORMAT_VERSION);
  EXPECT_EQ(header.algorithmId, format::AlgorithmID::ANS_COMPRESSOR);
  EXPECT_EQ(header.originalSize, 19u);
  EXPECT_EQ(header.originalChecksum,
            utils::crc32Calculator.calculate(sampleInput()));
  EXPECT_EQ(header.chunkCount, 1u);
  EXPECT_EQ(header.chunkSize, 19u);
  ASSERT_EQ(header.compressedSizes.size(), 1u);
  EXPECT_EQ(header.compressedSizes[0], 536u);
}

TEST(GoldenTest, CproOptimizedFixtureHeaderFields) {
  const format::FileHeader header =
      format::deserializeHeader(fromHex(kCproOptimizedFrameHex));
  EXPECT_EQ(header.formatVersion, format::FORMAT_VERSION);
  EXPECT_EQ(header.algorithmId, format::AlgorithmID::OPTIMIZED_COMPRESSOR);
  EXPECT_EQ(header.originalSize, 19u);
  EXPECT_EQ(header.originalChecksum,
            utils::crc32Calculator.calculate(sampleInput()));
  EXPECT_EQ(header.chunkCount, 1u);
  EXPECT_EQ(header.chunkSize, 19u);
  ASSERT_EQ(header.compressedSizes.size(), 1u);
  EXPECT_EQ(header.compressedSizes[0], 20u);
}